//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.6400
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 
namespace ClientWS.Stuffs {
    using System.Xml.Serialization;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Diagnostics;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ClientWSBinding", Namespace="http://clientws.signserver.org/")]
    public partial class ClientWSService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback processDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback processSODOperationCompleted;
        
        /// <remarks/>
        public ClientWSService(String url) {
            //this.Url = "http://tomicalab.com:8080/signserver/ClientWSService/ClientWS";
            this.Url = url;
        }
        
        /// <remarks/>
        public event processDataCompletedEventHandler processDataCompleted;
        
        /// <remarks/>
        public event processSODCompletedEventHandler processSODCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("processDataResponse", Namespace="http://clientws.signserver.org/")]
        public processDataResponse processData([System.Xml.Serialization.XmlElementAttribute("processData", Namespace="http://clientws.signserver.org/")] processData processData1) {
            object[] results = this.Invoke("processData", new object[] {
                        processData1});
            return ((processDataResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginprocessData(processData processData1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("processData", new object[] {
                        processData1}, callback, asyncState);
        }
        
        /// <remarks/>
        public processDataResponse EndprocessData(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((processDataResponse)(results[0]));
        }
        
        /// <remarks/>
        public void processDataAsync(processData processData1) {
            this.processDataAsync(processData1, null);
        }
        
        /// <remarks/>
        public void processDataAsync(processData processData1, object userState) {
            if ((this.processDataOperationCompleted == null)) {
                this.processDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnprocessDataOperationCompleted);
            }
            this.InvokeAsync("processData", new object[] {
                        processData1}, this.processDataOperationCompleted, userState);
        }
        
        private void OnprocessDataOperationCompleted(object arg) {
            if ((this.processDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.processDataCompleted(this, new processDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("processSODResponse", Namespace="http://clientws.signserver.org/")]
        public processSODResponse processSOD([System.Xml.Serialization.XmlElementAttribute("processSOD", Namespace="http://clientws.signserver.org/")] processSOD processSOD1) {
            object[] results = this.Invoke("processSOD", new object[] {
                        processSOD1});
            return ((processSODResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginprocessSOD(processSOD processSOD1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("processSOD", new object[] {
                        processSOD1}, callback, asyncState);
        }
        
        /// <remarks/>
        public processSODResponse EndprocessSOD(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((processSODResponse)(results[0]));
        }
        
        /// <remarks/>
        public void processSODAsync(processSOD processSOD1) {
            this.processSODAsync(processSOD1, null);
        }
        
        /// <remarks/>
        public void processSODAsync(processSOD processSOD1, object userState) {
            if ((this.processSODOperationCompleted == null)) {
                this.processSODOperationCompleted = new System.Threading.SendOrPostCallback(this.OnprocessSODOperationCompleted);
            }
            this.InvokeAsync("processSOD", new object[] {
                        processSOD1}, this.processSODOperationCompleted, userState);
        }
        
        private void OnprocessSODOperationCompleted(object arg) {
            if ((this.processSODCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.processSODCompleted(this, new processSODCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clientws.signserver.org/")]
    public partial class processData {
        
        private string workerField;
        
        private metadata[] metadataField;
        
        private byte[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string worker {
            get {
                return this.workerField;
            }
            set {
                this.workerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("metadata", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public metadata[] metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clientws.signserver.org/")]
    public partial class metadata {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clientws.signserver.org/")]
    public partial class processSODResponse {
        
        private sodResponse returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public sodResponse @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clientws.signserver.org/")]
    public partial class sodResponse : dataResponse {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sodResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clientws.signserver.org/")]
    public partial class dataResponse {
        
        private string archiveIdField;
        
        private byte[] dataField;
        
        private metadata[] metadataField;
        
        private int requestIdField;
        
        private byte[] signerCertificateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string archiveId {
            get {
                return this.archiveIdField;
            }
            set {
                this.archiveIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("metadata", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public metadata[] metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int requestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] signerCertificate {
            get {
                return this.signerCertificateField;
            }
            set {
                this.signerCertificateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clientws.signserver.org/")]
    public partial class dataGroup {
        
        private int idField;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clientws.signserver.org/")]
    public partial class sodRequest {
        
        private dataGroup[] dataGroupField;
        
        private string ldsVersionField;
        
        private string unicodeVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dataGroup", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dataGroup[] dataGroup {
            get {
                return this.dataGroupField;
            }
            set {
                this.dataGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ldsVersion {
            get {
                return this.ldsVersionField;
            }
            set {
                this.ldsVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string unicodeVersion {
            get {
                return this.unicodeVersionField;
            }
            set {
                this.unicodeVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clientws.signserver.org/")]
    public partial class processSOD {
        
        private string workerField;
        
        private metadata[] metadataField;
        
        private sodRequest sodDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string worker {
            get {
                return this.workerField;
            }
            set {
                this.workerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("metadata", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public metadata[] metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public sodRequest sodData {
            get {
                return this.sodDataField;
            }
            set {
                this.sodDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clientws.signserver.org/")]
    public partial class processDataResponse {
        
        private dataResponse returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dataResponse @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void processDataCompletedEventHandler(object sender, processDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class processDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal processDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public processDataResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((processDataResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void processSODCompletedEventHandler(object sender, processSODCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class processSODCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal processSODCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public processSODResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((processSODResponse)(this.results[0]));
            }
        }
    }
}
