//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4961
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



using FIS.Entities;
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://fis.vn/", ConfigurationName="ISAController")]
internal interface ISAController
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/GetSystemLog", ReplyAction="http://fis.vn/ISAController/GetSystemLogResponse")]
    string GetSystemLog(bool clearLog);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/GetServerInfo", ReplyAction="http://fis.vn/ISAController/GetServerInfoResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="serverInfo")]
    FIS.ServerInfo GetServerInfo(out FIS.Entities.CachedHashInfo cachedInfoHash, string clientLanguageID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/GetCurrentSessionInfo", ReplyAction="http://fis.vn/ISAController/GetCurrentSessionInfoResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="session")]
    FIS.Entities.Session GetCurrentSessionInfo();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/InitializeSessionID", ReplyAction="http://fis.vn/ISAController/InitializeSessionIDResponse")]
    void InitializeSessionID(string sessionID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/GetSessionUserInfo", ReplyAction="http://fis.vn/ISAController/GetSessionUserInfoResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="userInfo")]
    FIS.Entities.User GetSessionUserInfo();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/CheckRole", ReplyAction="http://fis.vn/ISAController/CheckRoleResponse")]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FIS.Entities.ImportModuleInfo))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FIS.Entities.ReportModuleInfo))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FIS.Entities.ChartModuleInfo))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FIS.Entities.MaintainModuleInfo))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FIS.Entities.SearchModuleInfo))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FIS.Entities.SwitchModuleInfo))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FIS.Entities.ExecProcModuleInfo))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FIS.Entities.AlertModuleInfo))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FIS.Entities.StatisticsModuleInfo))]
    void CheckRole(FIS.Entities.ModuleInfo moduleInfo);
    //add by TrungTT - 27.12.2012 - Userlog
    [System.ServiceModel.OperationContractAttribute(Action = "http://fis.vn/ISAController/ExecuteUsersLog", ReplyAction = "http://fis.vn/ISAController/ExecuteUsersLogResponse")]
    void ExecuteUsersLog(string moduleID, string moduleName);
    //End TrungTT
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/ListCurrentRoles", ReplyAction="http://fis.vn/ISAController/ListCurrentRolesResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="roles")]
    System.Collections.Generic.List<FIS.Entities.Role> ListCurrentRoles();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/ListCodesInfo", ReplyAction="http://fis.vn/ISAController/ListCodesInfoResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="codesInfo")]
    System.Collections.Generic.List<FIS.Entities.CodeInfo> ListCodesInfo();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/ListErrorsInfo", ReplyAction="http://fis.vn/ISAController/ListErrorsInfoResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="errorsInfo")]
    System.Collections.Generic.List<FIS.Entities.ErrorInfo> ListErrorsInfo();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/ListValidatesInfo", ReplyAction="http://fis.vn/ISAController/ListValidatesInfoResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="validatesInfo")]
    System.Collections.Generic.List<FIS.Entities.ValidateInfo> ListValidatesInfo();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/ListLanguage", ReplyAction="http://fis.vn/ISAController/ListLanguageResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="languageInfos")]
    System.Collections.Generic.List<FIS.Entities.LanguageInfo> ListLanguage(string languageID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/ListMenuItems", ReplyAction="http://fis.vn/ISAController/ListMenuItemsResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="menuItems")]
    System.Collections.Generic.List<FIS.Entities.MenuItemInfo> ListMenuItems();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/ListRibbonItems", ReplyAction="http://fis.vn/ISAController/ListRibbonItemsResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="ribbonItems")]
    System.Collections.Generic.List<FIS.Entities.RibbonItemInfo> ListRibbonItems();

    [System.ServiceModel.OperationContractAttribute(Action = "http://fis.vn/ISAController/ListExportHeaderInfo", ReplyAction = "http://fis.vn/ISAController/ListExportHeaderInfoResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name = "ExportHeaderInfos")]
    System.Collections.Generic.List<FIS.Entities.ExportHeader> ListExportHeaderInfo();

    [System.ServiceModel.OperationContractAttribute(Action = "http://fis.vn/ISAController/ListSysvarInfo", ReplyAction = "http://fis.vn/ISAController/ListSysvarInfoResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name = "SysvarInfos")]
    System.Collections.Generic.List<FIS.Entities.SysvarInfo> ListSysvarInfo();

    [System.ServiceModel.OperationContractAttribute(Action = "http://fis.vn/ISAController/ListGroupSummaryInfo", ReplyAction = "http://fis.vn/ISAController/ListGroupSummaryInfoResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name = "groupSummaryInfos")]
    System.Collections.Generic.List<FIS.Entities.GroupSummaryInfo> ListGroupSummaryInfo();

    [System.ServiceModel.OperationContractAttribute(Action = "http://fis.vn/ISAController/ListModuleInfo", ReplyAction = "http://fis.vn/ISAController/ListModuleInfoResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="moduleInfos")]
    System.Collections.Generic.List<FIS.Entities.ModuleInfo> ListModuleInfo();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/ListBatchInfo", ReplyAction="http://fis.vn/ISAController/ListBatchInfoResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="moduleInfos")]
    System.Collections.Generic.List<FIS.Entities.BatchInfo> ListBatchInfo(string moduleID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/ListModuleField", ReplyAction="http://fis.vn/ISAController/ListModuleFieldResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="moduleFields")]
    System.Collections.Generic.List<FIS.Entities.ModuleFieldInfo> ListModuleField(out int endRow, int startRow);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/GetDataSource", ReplyAction="http://fis.vn/ISAController/GetDataSourceResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="sourceData")]
    System.Collections.Generic.List<FIS.Entities.NameValueItem> GetDataSource(string sourceName, System.Collections.Generic.List<string> values);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/TerminalCurrentSession", ReplyAction="http://fis.vn/ISAController/TerminalCurrentSessionResponse")]
    void TerminalCurrentSession();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/CreateUserSession", ReplyAction="http://fis.vn/ISAController/CreateUserSessionResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="session")]
    FIS.Entities.Session CreateUserSession(string userName, string password);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/ListSearchButton", ReplyAction="http://fis.vn/ISAController/ListSearchButtonResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="buttons")]
    System.Collections.Generic.List<FIS.Entities.ButtonInfo> ListSearchButton();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/ListSearchButtonParam", ReplyAction="http://fis.vn/ISAController/ListSearchButtonParamResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="searchButtonParamsInfo")]
    System.Collections.Generic.List<FIS.Entities.ButtonParamInfo> ListSearchButtonParam();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/ExecuteSwitchModule", ReplyAction="http://fis.vn/ISAController/ExecuteSwitchModuleResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="targetModule")]
    string ExecuteSwitchModule(string moduleID, string subModule, System.Collections.Generic.List<string> values);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/ExecuteMaintainQuery", ReplyAction="http://fis.vn/ISAController/ExecuteMaintainQueryResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="executeResult")]
    FIS.Base.DataContainer ExecuteMaintainQuery(string moduleID, string subModule, System.Collections.Generic.List<string> values);

    [System.ServiceModel.OperationContractAttribute(Action = "http://fis.vn/ISAController/ExecuteTransQuery", ReplyAction = "http://fis.vn/ISAController/ExecuteTransQueryResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name = "executeResult")]
    FIS.Base.DataContainer ExecuteTransQuery(string moduleID, string subModule, System.Collections.Generic.List<string> values);
    
    //Tudq them

    [System.ServiceModel.OperationContractAttribute(Action = "http://fis.vn/ISAController/GetTreeViewStore", ReplyAction = "http://fis.vn/ISAController/GetTreeViewStoreResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name = "executeResult")]
    FIS.Base.DataContainer GetTreeViewStore(System.Collections.Generic.List<string> values);


    [System.ServiceModel.OperationContractAttribute(Action = "http://fis.vn/ISAController/GetTreeViewLang", ReplyAction = "http://fis.vn/ISAController/GetTreeViewLangResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name = "executeResult")]
    FIS.Base.DataContainer GetTreeViewLang(System.Collections.Generic.List<string> values);
    //
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/ExecuteReport", ReplyAction="http://fis.vn/ISAController/ExecuteReportResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="container")]
    FIS.Base.DataContainer ExecuteReport(string moduleID, string subModule, System.Collections.Generic.List<string> values);

    //add by TrungTT - 10.11.2011 - Maintain report
    [System.ServiceModel.OperationContractAttribute(Action = "http://fis.vn/ISAController/ExecuteMaintainReport", ReplyAction = "http://fis.vn/ISAController/ExecuteMaintainReportResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name = "container")]
    FIS.Base.DataContainer ExecuteMaintainReport(string moduleID, string subModule, System.Collections.Generic.List<string> values);
    //end TrungTT

    //add by TrungTT - 8.11.2011 - Auto Report
    [System.ServiceModel.OperationContractAttribute(Action = "http://fis.vn/ISAController/ExecuteAutoReport", ReplyAction = "http://fis.vn/ISAController/ExecuteAutoReportResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="container")]
    FIS.Base.DataContainer ExecuteAutoReport(string moduleID, string batchName, System.Collections.Generic.List<string> values);
    //End TrungTT
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/ExecuteMarket", ReplyAction="http://fis.vn/ISAController/ExecuteMarketResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="container")]
    FIS.Base.DataContainer ExecuteMarket();

    //add bytrungtt - 23.09.2011 - Menu Skins
    [System.ServiceModel.OperationContractAttribute(Action = "http://fis.vn/ISAController/ExecuteLoadSkins", ReplyAction = "http://fis.vn/ISAController/ExecuteLoadSkinsResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name = "container")]
    FIS.Base.DataContainer ExecuteLoadSkins();
    //end TrungTT

    //add bytrungtt - 27.09.2011 - Get System Date
    [System.ServiceModel.OperationContractAttribute(Action = "http://fis.vn/ISAController/GetSysDate", ReplyAction = "http://fis.vn/ISAController/GetSysDateResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name = "container")]
    FIS.Base.DataContainer GetSysDate();
    //end TrungTT

    //add bytrungtt - 26.09.2011 - Load Current Skins
    [System.ServiceModel.OperationContractAttribute(Action = "http://fis.vn/ISAController/ExecuteLoadCurrentSkins", ReplyAction = "http://fis.vn/ISAController/ExecuteLoadCurrentSkinsResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name = "container")]
    FIS.Base.DataContainer ExecuteLoadCurrentSkins();
    //end TrungTT

    //add by trungtt - 25.08.2011 - update market
    [System.ServiceModel.OperationContractAttribute(Action = "http://fis.vn/ISAController/UpdateMarket", ReplyAction = "http://fis.vn/ISAController/UpdateMarketResponse")]
    void UpdateMarket(System.Collections.Generic.List<string> values);
    //end trungtt

    //add by trungtt - 26.09.2011 - Change Skins
    [System.ServiceModel.OperationContractAttribute(Action = "http://fis.vn/ISAController/ExecuteChangeSkins", ReplyAction = "http://fis.vn/ISAController/ExecuteChangeSkinsResponse")]
    void ExecuteChangeSkins(System.Collections.Generic.List<string> values);
    //end trungtt

    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/ExecuteDownloadFile", ReplyAction="http://fis.vn/ISAController/ExecuteDownloadFileResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="container")]
    FIS.Base.DataContainer ExecuteDownloadFile(string moduleID,string subModule,System.Collections.Generic.List<string> values);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/ExecuteImport", ReplyAction="http://fis.vn/ISAController/ExecuteImportResponse")]
    void ExecuteImport(string moduleID, string subModule, System.Collections.Generic.List<string> values);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/ExecuteMaintain", ReplyAction="http://fis.vn/ISAController/ExecuteMaintainResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="container")]
    FIS.Base.DataContainer ExecuteMaintain(string moduleID, string subModule, System.Collections.Generic.List<string> values);

    //add by trungtt - 23.8.2013
    [System.ServiceModel.OperationContractAttribute(Action = "http://fis.vn/ISAController/ExecApprove", ReplyAction = "http://fis.vn/ISAController/ExecApproveResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name = "container")]
    FIS.Base.DataContainer ExecApprove(string moduleID, string subModule,string secID, System.Collections.Generic.List<string> values);
    //end trungtt

    //[System.ServiceModel.OperationContractAttribute(Action = "http://fis.vn/ISAController/ExecuteApproved", ReplyAction = "http://fis.vn/ISAController/ExecuteApprovedResponse")]
    //[return: System.ServiceModel.MessageParameterAttribute(Name = "container")]
    //FIS.Base.DataContainer ExecuteApproved(string moduleID, string subModule, System.Collections.Generic.List<string> values);


    //add by TrungTT - 08.12.2011 - Edit Grid's column Layout
    [System.ServiceModel.OperationContractAttribute(Action = "http://fis.vn/ISAController/GetExtraCurrentUserProfile", ReplyAction = "http://fis.vn/ISAController/GetExtraCurrentUserProfileResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name = "extraValue")]
    string GetExtraCurrentUserProfile(string extraProperty);

    [System.ServiceModel.OperationContractAttribute(Action = "http://fis.vn/ISAController/SetExtraCurrentUserProfile", ReplyAction = "http://fis.vn/ISAController/SetExtraCurrentUserProfileResponse")]
    void SetExtraCurrentUserProfile(string extraProperty,string extraValue);
    
    //End TrungTT

    //add by TrungTT - 9.11.2011 - Bactch put msg
    [System.ServiceModel.OperationContractAttribute(Action = "http://fis.vn/ISAController/ExecuteBatchPutMsg", ReplyAction = "http://fis.vn/ISAController/ExecuteBatchPutMsgResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name = "container")]
    FIS.Base.DataContainer ExecuteBatchPutMsg(string moduleID, string storeData, System.Collections.Generic.List<string> values);
    //end TrungTT
    
    //add by TrungTT - 28.11.2011 - Execute procedure fill dataset
    [System.ServiceModel.OperationContractAttribute(Action = "http://fis.vn/ISAController/ExecuteProcedureFillDataset", ReplyAction = "http://fis.vn/ISAController/ExecuteProcedureFillDatasetResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name = "container")]
    FIS.Base.DataContainer ExecuteProcedureFillDataset(string storeData, System.Collections.Generic.List<string> values);
    //end TrungTT

    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/ExecuteChartMaster", ReplyAction="http://fis.vn/ISAController/ExecuteChartMasterResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="executeResult")]
    FIS.Base.DataContainer ExecuteChartMaster(string moduleID, string subModule, System.Collections.Generic.List<string> values);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/ExecuteProcedure", ReplyAction="http://fis.vn/ISAController/ExecuteProcedureResponse")]
    void ExecuteProcedure(string moduleID, string subModule, System.Collections.Generic.List<string> values);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/ExecuteInstallModule", ReplyAction="http://fis.vn/ISAController/ExecuteInstallModuleResponse")]
    void ExecuteInstallModule(string modulePackageData);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/ExecuteUninstallModule", ReplyAction="http://fis.vn/ISAController/ExecuteUninstallModuleResponse")]
    void ExecuteUninstallModule(string moduleID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/ExecuteSaveLanguage", ReplyAction="http://fis.vn/ISAController/ExecuteSaveLanguageResponse")]
    void ExecuteSaveLanguage(string langID, string langName, string langValue);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/ExecuteGenerateModulePackage", ReplyAction="http://fis.vn/ISAController/ExecuteGenerateModulePackageResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="generatedPackage")]
    string ExecuteGenerateModulePackage(string moduleID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/ValidateFieldInfoSyntax", ReplyAction="http://fis.vn/ISAController/ValidateFieldInfoSyntaxResponse")]
    void ValidateFieldInfoSyntax(string moduleID, string subModule, string fieldID, System.Collections.Generic.List<string> values);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/CallbackQuery", ReplyAction="http://fis.vn/ISAController/CallbackQueryResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="executeResult")]
    FIS.Base.DataContainer CallbackQuery(string moduleID, string callbackFieldID, System.Collections.Generic.List<string> values);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/ListOracleParameter", ReplyAction="http://fis.vn/ISAController/ListOracleParameterResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="oracleParams")]
    System.Collections.Generic.List<FIS.Entities.OracleParam> ListOracleParameter();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/FetchAllSearchResult", ReplyAction="http://fis.vn/ISAController/FetchAllSearchResultResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="searchResult")]
    FIS.Base.DataContainer FetchAllSearchResult(string moduleID, string subModule, string searchResultKey, System.DateTime searchTime, int fromRow);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/FetchSearchResult", ReplyAction="http://fis.vn/ISAController/FetchSearchResultResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="searchResult")]
    FIS.Base.DataContainer FetchSearchResult(out int bufferSize, out int minPage, out int maxPage, out int startRow, string moduleID, string subModule, string searchResultKey, System.DateTime searchTime, int selectedPage, int maxPageSize);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/DisposeSearchResult", ReplyAction="http://fis.vn/ISAController/DisposeSearchResultResponse")]
    void DisposeSearchResult(string moduleID, string subModule, string searchResultKey, System.DateTime searchTime);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/GetSearchStatistic", ReplyAction="http://fis.vn/ISAController/GetSearchStatisticResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="searchStatistic")]
    FIS.Base.DataContainer GetSearchStatistic(string moduleID, string subModule, FIS.Entities.SearchConditionInstance conditionIntance, System.Collections.Generic.List<FIS.Entities.SearchConditionInstance> staticConditionInstances);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/ExecuteSearch", ReplyAction="http://fis.vn/ISAController/ExecuteSearchResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="searchResultKey")]
    string ExecuteSearch(out System.DateTime searchTime, string moduleID, string subModule, FIS.Entities.SearchConditionInstance conditionIntance, System.Collections.Generic.List<FIS.Entities.SearchConditionInstance> staticConditionInstances);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/ExecuteSearchEdit", ReplyAction="http://fis.vn/ISAController/ExecuteSearchEditResponse")]
    void ExecuteSearchEdit(string moduleID, string subModule, System.Collections.Generic.List<string> values);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/ListGroupRoles", ReplyAction="http://fis.vn/ISAController/ListGroupRolesResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="roles")]
    System.Collections.Generic.List<FIS.Entities.Role> ListGroupRoles(int groupID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/ListUserRoles", ReplyAction="http://fis.vn/ISAController/ListUserRolesResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="roles")]
    System.Collections.Generic.List<FIS.Entities.Role> ListUserRoles(int userID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/SaveGroupRoles", ReplyAction="http://fis.vn/ISAController/SaveGroupRolesResponse")]
    void SaveGroupRoles(System.Collections.Generic.List<FIS.Entities.Role> roles, int groupID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/SaveUserRoles", ReplyAction="http://fis.vn/ISAController/SaveUserRolesResponse")]
    void SaveUserRoles(System.Collections.Generic.List<FIS.Entities.Role> roles, int userID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/ExecuteAlert", ReplyAction="http://fis.vn/ISAController/ExecuteAlertResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="alertResult")]
    FIS.Base.DataContainer ExecuteAlert(string moduleID, string subModule);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/ExecuteBatch", ReplyAction="http://fis.vn/ISAController/ExecuteBatchResponse")]
    void ExecuteBatch(string moduleID, string batchName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/ExecuteBatchMarket", ReplyAction="http://fis.vn/ISAController/ExecuteBatchMarketResponse")]
    void ExecuteBatchMarket(string moduleID, string batchName, string market);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/ExecuteAlertClick", ReplyAction="http://fis.vn/ISAController/ExecuteAlertClickResponse")]
    void ExecuteAlertClick(string moduleID, string subModule);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/GetListSource", ReplyAction="http://fis.vn/ISAController/GetListSourceResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="listSource")]
    System.Collections.Generic.List<FIS.Entities.NameValueItem> GetListSource(string moduleID, string subModule, string fieldID, System.Collections.Generic.List<string> values);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/SaveLayout", ReplyAction="http://fis.vn/ISAController/SaveLayoutResponse")]
    void SaveLayout(string moduleID, string subModule, string languageID, string layout);
    
    //[System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/SaveFile", ReplyAction="http://fis.vn/ISAController/SaveFileResponse")]
    //void SaveFile(string filename, byte[] file);

    [System.ServiceModel.OperationContractAttribute(Action = "http://fis.vn/ISAController/SaveFile", ReplyAction = "http://fis.vn/ISAController/SaveFileResponse")]
    void SaveFile(FileUpload file);

    //trungtt - 20.12.2013 - sign file
    [System.ServiceModel.OperationContractAttribute(Action = "http://fis.vn/ISAController/SignFile", ReplyAction = "http://fis.vn/ISAController/SignFileResponse")]
    void SignFile(string filename, string certificateinfo, string worker, byte[] file);
    //end trungtt
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/ExecuteSQL", ReplyAction="http://fis.vn/ISAController/ExecuteSQLResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="container")]
    FIS.Base.DataContainer ExecuteSQL(string sqlQuery);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/ExecuteStoreProcedure", ReplyAction="http://fis.vn/ISAController/ExecuteStoreProcedureResponse")]
    void ExecuteStoreProcedure(string storeProcedure, System.Collections.Generic.List<string> values);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/ResetCache", ReplyAction="http://fis.vn/ISAController/ResetCacheResponse")]
    void ResetCache();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/CheckUpdate", ReplyAction="http://fis.vn/ISAController/CheckUpdateResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="fileContent")]
    string CheckUpdate(string clientVersion);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/NewsInfo", ReplyAction="http://fis.vn/ISAController/NewsInfoResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="newsInfo")]
    System.Collections.Generic.List<FIS.Entities.NewsInfo> NewsInfo();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/GetCurrentUserProfile", ReplyAction="http://fis.vn/ISAController/GetCurrentUserProfileResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="userProfile")]
    FIS.Entities.UserProfile GetCurrentUserProfile();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/ListUsersInGroup", ReplyAction="http://fis.vn/ISAController/ListUsersInGroupResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="users")]
    System.Collections.Generic.List<FIS.Entities.User> ListUsersInGroup(int groupID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/ForceLoadModule", ReplyAction="http://fis.vn/ISAController/ForceLoadModuleResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="modulesInfo")]
    System.Collections.Generic.List<FIS.Entities.ModuleInfo> ForceLoadModule(out System.Collections.Generic.List<FIS.Entities.ModuleFieldInfo> fieldsInfo, out System.Collections.Generic.List<FIS.Entities.ButtonInfo> buttonsInfo, out System.Collections.Generic.List<FIS.Entities.ButtonParamInfo> buttonParamsInfo, out System.Collections.Generic.List<FIS.Entities.LanguageInfo> languageInfo, out System.Collections.Generic.List<FIS.Entities.OracleParam> oracleParamsInfo, string moduleID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fis.vn/ISAController/ExecuteStatistics", ReplyAction="http://fis.vn/ISAController/ExecuteStatisticsResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="searchResultKey")]
    string ExecuteStatistics(out System.DateTime searchTime, string moduleID, string subModule, System.Collections.Generic.List<string> values);

    //TuDQ sua
    [System.ServiceModel.OperationContractAttribute(Action = "http://fis.vn/ISAController/ExecuteChartQuery", ReplyAction = "http://fis.vn/ISAController/ExecuteChartQueryResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name = "chartResult")]
    System.Data.DataSet ExecuteChartQuery(string moduleID, string subModule, System.Collections.Generic.List<string> values);

    [System.ServiceModel.OperationContractAttribute(Action = "http://fis.vn/ISAController/GetChartInf", ReplyAction = "http://fis.vn/ISAController/GetChartInfResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name = "chartResult")]
    System.Data.DataSet GetChartInf(System.Collections.Generic.List<string> values);
    //End

    [System.ServiceModel.OperationContractAttribute(Action = "http://fis.vn/ISAController/GetModImport", ReplyAction = "http://fis.vn/ISAController/GetModImportResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name = "executeResult")]
    System.Data.DataSet GetModImport(string rptID);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
internal interface ISAControllerChannel : ISAController, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
internal partial class SAControllerClient : System.ServiceModel.ClientBase<ISAController>, ISAController
{
    
    public SAControllerClient()
    {
    }
    
    public SAControllerClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public SAControllerClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SAControllerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SAControllerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }

    public System.Data.DataSet GetModImport(string rptID)
    {
        return base.Channel.GetModImport(rptID);
    }

    public string GetSystemLog(bool clearLog)
    {
        return base.Channel.GetSystemLog(clearLog);
    }
    
    public FIS.ServerInfo GetServerInfo(out FIS.Entities.CachedHashInfo cachedInfoHash, string clientLanguageID)
    {
        return base.Channel.GetServerInfo(out cachedInfoHash, clientLanguageID);
    }
    
    public FIS.Entities.Session GetCurrentSessionInfo()
    {
        return base.Channel.GetCurrentSessionInfo();
    }
    
    public void InitializeSessionID(string sessionID)
    {
        base.Channel.InitializeSessionID(sessionID);
    }
    
    public FIS.Entities.User GetSessionUserInfo()
    {
        return base.Channel.GetSessionUserInfo();
    }
    
    public void CheckRole(FIS.Entities.ModuleInfo moduleInfo)
    {
        base.Channel.CheckRole(moduleInfo);
    }
    //add by TrungTT - 27.12.2012 - Userlog
    public void ExecuteUsersLog(string moduleID, string moduleName)
    {
        base.Channel.ExecuteUsersLog(moduleID, moduleName);
    }
    //End TrungTT
    public System.Collections.Generic.List<FIS.Entities.Role> ListCurrentRoles()
    {
        return base.Channel.ListCurrentRoles();
    }
    
    public System.Collections.Generic.List<FIS.Entities.CodeInfo> ListCodesInfo()
    {
        return base.Channel.ListCodesInfo();
    }
    
    public System.Collections.Generic.List<FIS.Entities.ErrorInfo> ListErrorsInfo()
    {
        return base.Channel.ListErrorsInfo();
    }
    
    public System.Collections.Generic.List<FIS.Entities.ValidateInfo> ListValidatesInfo()
    {
        return base.Channel.ListValidatesInfo();
    }
    
    public System.Collections.Generic.List<FIS.Entities.LanguageInfo> ListLanguage(string languageID)
    {
        return base.Channel.ListLanguage(languageID);
    }
    
    public System.Collections.Generic.List<FIS.Entities.MenuItemInfo> ListMenuItems()
    {
        return base.Channel.ListMenuItems();
    }
    
    public System.Collections.Generic.List<FIS.Entities.RibbonItemInfo> ListRibbonItems()
    {
        return base.Channel.ListRibbonItems();
    }

    public System.Collections.Generic.List<FIS.Entities.GroupSummaryInfo> ListGroupSummaryInfo()
    {
        return base.Channel.ListGroupSummaryInfo();
    }

    public System.Collections.Generic.List<FIS.Entities.ExportHeader> ListExportHeaderInfo()
    {
        return base.Channel.ListExportHeaderInfo();
    }

    public System.Collections.Generic.List<FIS.Entities.SysvarInfo> ListSysvarInfo()
    {
        return base.Channel.ListSysvarInfo();
    }

    public System.Collections.Generic.List<FIS.Entities.ModuleInfo> ListModuleInfo()
    {
        return base.Channel.ListModuleInfo();
    }
    
    public System.Collections.Generic.List<FIS.Entities.BatchInfo> ListBatchInfo(string moduleID)
    {
        return base.Channel.ListBatchInfo(moduleID);
    }
    
    public System.Collections.Generic.List<FIS.Entities.ModuleFieldInfo> ListModuleField(out int endRow, int startRow)
    {
        return base.Channel.ListModuleField(out endRow, startRow);
    }
    
    public System.Collections.Generic.List<FIS.Entities.NameValueItem> GetDataSource(string sourceName, System.Collections.Generic.List<string> values)
    {
        return base.Channel.GetDataSource(sourceName, values);
    }
    
    public void TerminalCurrentSession()
    {
        base.Channel.TerminalCurrentSession();
    }
    
    public FIS.Entities.Session CreateUserSession(string userName, string password)
    {
        return base.Channel.CreateUserSession(userName, password);
    }
    
    public System.Collections.Generic.List<FIS.Entities.ButtonInfo> ListSearchButton()
    {
        return base.Channel.ListSearchButton();
    }
    
    public System.Collections.Generic.List<FIS.Entities.ButtonParamInfo> ListSearchButtonParam()
    {
        return base.Channel.ListSearchButtonParam();
    }
    
    public string ExecuteSwitchModule(string moduleID, string subModule, System.Collections.Generic.List<string> values)
    {
        return base.Channel.ExecuteSwitchModule(moduleID, subModule, values);
    }
    
    public FIS.Base.DataContainer ExecuteMaintainQuery(string moduleID, string subModule, System.Collections.Generic.List<string> values)
    {
        return base.Channel.ExecuteMaintainQuery(moduleID, subModule, values);
    }

    public FIS.Base.DataContainer ExecuteTransQuery(string moduleID, string subModule, System.Collections.Generic.List<string> values)
    {
        return base.Channel.ExecuteTransQuery(moduleID, subModule, values);
    }

    //TUDQ them

    public FIS.Base.DataContainer GetTreeViewStore(System.Collections.Generic.List<string> values)
    {
        return base.Channel.GetTreeViewStore(values);
    }

    public FIS.Base.DataContainer GetTreeViewLang(System.Collections.Generic.List<string> values)
    {
        return base.Channel.GetTreeViewLang(values);
    }

    //
    
    public FIS.Base.DataContainer ExecuteReport(string moduleID, string subModule, System.Collections.Generic.List<string> values)
    {
        return base.Channel.ExecuteReport(moduleID, subModule, values);
    }
    
    //add by TrungTT - 10.11.2011 - Maintain Report
    public FIS.Base.DataContainer ExecuteMaintainReport(string moduleID, string subModule, System.Collections.Generic.List<string> values)
    {
        return base.Channel.ExecuteMaintainReport(moduleID, subModule, values);
    }
    //End TrungTT
    //add by TrungTT - 8.11.2011 - Auto Report
    public FIS.Base.DataContainer ExecuteAutoReport(string moduleID, string batchName, System.Collections.Generic.List<string> values)
    {
        return base.Channel.ExecuteAutoReport(moduleID, batchName, values);
    }
    //End TrungTT
    
    public FIS.Base.DataContainer ExecuteMarket()
    {
        return base.Channel.ExecuteMarket();
    }

    //add by TrungTT - 23.09.2011 - Menu Skins
    public FIS.Base.DataContainer ExecuteLoadSkins()
    {
        return base.Channel.ExecuteLoadSkins();
    }
    //end TrungTT

    //add by TrungTT - 27.09.2011 - Get System Date
    public FIS.Base.DataContainer GetSysDate()
    {
        return base.Channel.GetSysDate();
    }

    //add by TrungTT - 26.09.2011 - Load Current Skin
    public FIS.Base.DataContainer ExecuteLoadCurrentSkins()
    {
        return base.Channel.ExecuteLoadCurrentSkins();
    }
    //end TrungTT

    //add by trungtt - 25.08.2011 - Update Market
    public void UpdateMarket(System.Collections.Generic.List<string> values)
    {
        base.Channel.UpdateMarket(values);
    }
    //end trungtt

    //add by TrungTT - 26.09.2011 - Change Skins
    public void ExecuteChangeSkins(System.Collections.Generic.List<string> values)
    {
        base.Channel.ExecuteChangeSkins(values);
    }
    //End TrungTT

    public FIS.Base.DataContainer ExecuteDownloadFile(string moduleID, string subModule,System.Collections.Generic.List<string> values)
    {
        return base.Channel.ExecuteDownloadFile(moduleID, subModule, values);
    }
    
    public void ExecuteImport(string moduleID, string subModule, System.Collections.Generic.List<string> values)
    {
        base.Channel.ExecuteImport(moduleID, subModule, values);
    }
    
    public FIS.Base.DataContainer ExecuteMaintain(string moduleID, string subModule, System.Collections.Generic.List<string> values)
    {
        return base.Channel.ExecuteMaintain(moduleID, subModule, values);
    }

    //add by trungtt - 28.3.2013
    public FIS.Base.DataContainer ExecApprove(string moduleID, string subModule,string secID, System.Collections.Generic.List<string> values)
    {
        return base.Channel.ExecApprove(moduleID, subModule,secID, values);
    }
    //end trungtt

    //public FIS.Base.DataContainer ExecuteApproved(string moduleID, string subModule, System.Collections.Generic.List<string> values)
    //{
    //    return base.Channel.ExecuteApproved(moduleID, subModule, values);
    //}

    //add by TrungTT - 08.12.2011 - Edit Grid's column layout 
    public string GetExtraCurrentUserProfile(string extraProperty)
    {
        return base.Channel.GetExtraCurrentUserProfile(extraProperty);
    }
    public void SetExtraCurrentUserProfile(string extraProperty,string extraValue)
    {
        base.Channel.SetExtraCurrentUserProfile(extraProperty, extraValue);
    }
    //end trungtt

    //add by TrungTT - 9.11.2011 - Batch put Msg
    public FIS.Base.DataContainer ExecuteBatchPutMsg(string moduleID, string storeData, System.Collections.Generic.List<string> values)
    {
        return base.Channel.ExecuteBatchPutMsg(moduleID, storeData, values);
    }
    //End TrungTT

    //add by TrungTT - 28.11.2011 - Execute Procedure Fill Dataset
    public FIS.Base.DataContainer ExecuteProcedureFillDataset(string storeData, System.Collections.Generic.List<string> values)
    {
        return base.Channel.ExecuteProcedureFillDataset(storeData, values);
    }
    //End TrungTT

    public FIS.Base.DataContainer ExecuteChartMaster(string moduleID, string subModule, System.Collections.Generic.List<string> values)
    {
        return base.Channel.ExecuteChartMaster(moduleID, subModule, values);
    }
    
    public void ExecuteProcedure(string moduleID, string subModule, System.Collections.Generic.List<string> values)
    {
        base.Channel.ExecuteProcedure(moduleID, subModule, values);
    }
    
    public void ExecuteInstallModule(string modulePackageData)
    {
        base.Channel.ExecuteInstallModule(modulePackageData);
    }
    
    public void ExecuteUninstallModule(string moduleID)
    {
        base.Channel.ExecuteUninstallModule(moduleID);
    }
    
    public void ExecuteSaveLanguage(string langID, string langName, string langValue)
    {
        base.Channel.ExecuteSaveLanguage(langID, langName, langValue);
    }
    
    public string ExecuteGenerateModulePackage(string moduleID)
    {
        return base.Channel.ExecuteGenerateModulePackage(moduleID);
    }
    
    public void ValidateFieldInfoSyntax(string moduleID, string subModule, string fieldID, System.Collections.Generic.List<string> values)
    {
        base.Channel.ValidateFieldInfoSyntax(moduleID, subModule, fieldID, values);
    }
    
    public FIS.Base.DataContainer CallbackQuery(string moduleID, string callbackFieldID, System.Collections.Generic.List<string> values)
    {
        return base.Channel.CallbackQuery(moduleID, callbackFieldID, values);
    }
    
    public System.Collections.Generic.List<FIS.Entities.OracleParam> ListOracleParameter()
    {
        return base.Channel.ListOracleParameter();
    }
    
    public FIS.Base.DataContainer FetchAllSearchResult(string moduleID, string subModule, string searchResultKey, System.DateTime searchTime, int fromRow)
    {
        return base.Channel.FetchAllSearchResult(moduleID, subModule, searchResultKey, searchTime, fromRow);
    }
    
    public FIS.Base.DataContainer FetchSearchResult(out int bufferSize, out int minPage, out int maxPage, out int startRow, string moduleID, string subModule, string searchResultKey, System.DateTime searchTime, int selectedPage, int maxPageSize)
    {
        return base.Channel.FetchSearchResult(out bufferSize, out minPage, out maxPage, out startRow, moduleID, subModule, searchResultKey, searchTime, selectedPage, maxPageSize);
    }
    
    public void DisposeSearchResult(string moduleID, string subModule, string searchResultKey, System.DateTime searchTime)
    {
        base.Channel.DisposeSearchResult(moduleID, subModule, searchResultKey, searchTime);
    }
    
    public FIS.Base.DataContainer GetSearchStatistic(string moduleID, string subModule, FIS.Entities.SearchConditionInstance conditionIntance, System.Collections.Generic.List<FIS.Entities.SearchConditionInstance> staticConditionInstances)
    {
        return base.Channel.GetSearchStatistic(moduleID, subModule, conditionIntance, staticConditionInstances);
    }
    
    public string ExecuteSearch(out System.DateTime searchTime, string moduleID, string subModule, FIS.Entities.SearchConditionInstance conditionIntance, System.Collections.Generic.List<FIS.Entities.SearchConditionInstance> staticConditionInstances)
    {
        return base.Channel.ExecuteSearch(out searchTime, moduleID, subModule, conditionIntance, staticConditionInstances);
    }
    
    public void ExecuteSearchEdit(string moduleID, string subModule, System.Collections.Generic.List<string> values)
    {
        base.Channel.ExecuteSearchEdit(moduleID, subModule, values);
    }
    
    public System.Collections.Generic.List<FIS.Entities.Role> ListGroupRoles(int groupID)
    {
        return base.Channel.ListGroupRoles(groupID);
    }
    
    public System.Collections.Generic.List<FIS.Entities.Role> ListUserRoles(int userID)
    {
        return base.Channel.ListUserRoles(userID);
    }
    
    public void SaveGroupRoles(System.Collections.Generic.List<FIS.Entities.Role> roles, int groupID)
    {
        base.Channel.SaveGroupRoles(roles, groupID);
    }
    
    public void SaveUserRoles(System.Collections.Generic.List<FIS.Entities.Role> roles, int userID)
    {
        base.Channel.SaveUserRoles(roles, userID);
    }
    
    public FIS.Base.DataContainer ExecuteAlert(string moduleID, string subModule)
    {
        return base.Channel.ExecuteAlert(moduleID, subModule);
    }
    
    public void ExecuteBatch(string moduleID, string batchName)
    {
        base.Channel.ExecuteBatch(moduleID, batchName);
    }
    
    public void ExecuteBatchMarket(string moduleID, string batchName, string market)
    {
        base.Channel.ExecuteBatchMarket(moduleID, batchName, market);
    }
    
    public void ExecuteAlertClick(string moduleID, string subModule)
    {
        base.Channel.ExecuteAlertClick(moduleID, subModule);
    }
    
    public System.Collections.Generic.List<FIS.Entities.NameValueItem> GetListSource(string moduleID, string subModule, string fieldID, System.Collections.Generic.List<string> values)
    {
        return base.Channel.GetListSource(moduleID, subModule, fieldID, values);
    }
    
    public void SaveLayout(string moduleID, string subModule, string languageID, string layout)
    {
        base.Channel.SaveLayout(moduleID, subModule, languageID, layout);
    }

    //public void SaveFile(string filename, byte[] file)
    //{
    //    base.Channel.SaveFile(filename, file);
    //}

    public void SaveFile(FileUpload file)
    {
        base.Channel.SaveFile(file);
    }

    //trungtt - 20.12.2013 - sign file
    public void SignFile(string filename, string certificateinfo, string worker, byte[] file)
    {
        base.Channel.SignFile(filename, certificateinfo, worker, file);
    }
    //end trungtt
    
    public FIS.Base.DataContainer ExecuteSQL(string sqlQuery)
    {
        return base.Channel.ExecuteSQL(sqlQuery);
    }
    
    public void ExecuteStoreProcedure(string storeProcedure, System.Collections.Generic.List<string> values)
    {
        base.Channel.ExecuteStoreProcedure(storeProcedure, values);
    }
    
    public void ResetCache()
    {
        base.Channel.ResetCache();
    }
    
    public string CheckUpdate(string clientVersion)
    {
        return base.Channel.CheckUpdate(clientVersion);
    }
    
    public System.Collections.Generic.List<FIS.Entities.NewsInfo> NewsInfo()
    {
        return base.Channel.NewsInfo();
    }
    
    public FIS.Entities.UserProfile GetCurrentUserProfile()
    {
        return base.Channel.GetCurrentUserProfile();
    }
    
    public System.Collections.Generic.List<FIS.Entities.User> ListUsersInGroup(int groupID)
    {
        return base.Channel.ListUsersInGroup(groupID);
    }
    
    public System.Collections.Generic.List<FIS.Entities.ModuleInfo> ForceLoadModule(out System.Collections.Generic.List<FIS.Entities.ModuleFieldInfo> fieldsInfo, out System.Collections.Generic.List<FIS.Entities.ButtonInfo> buttonsInfo, out System.Collections.Generic.List<FIS.Entities.ButtonParamInfo> buttonParamsInfo, out System.Collections.Generic.List<FIS.Entities.LanguageInfo> languageInfo, out System.Collections.Generic.List<FIS.Entities.OracleParam> oracleParamsInfo, string moduleID)
    {
        return base.Channel.ForceLoadModule(out fieldsInfo, out buttonsInfo, out buttonParamsInfo, out languageInfo, out oracleParamsInfo, moduleID);
    }
    
    public string ExecuteStatistics(out System.DateTime searchTime, string moduleID, string subModule, System.Collections.Generic.List<string> values)
    {
        return base.Channel.ExecuteStatistics(out searchTime, moduleID, subModule, values);
    }
    //TuDQ sua
    public System.Data.DataSet ExecuteChartQuery(string moduleID, string subModule, System.Collections.Generic.List<string> values)
    {
        return base.Channel.ExecuteChartQuery(moduleID, subModule, values);
    }

    public System.Data.DataSet GetChartInf(System.Collections.Generic.List<string> values)
    {
        return base.Channel.GetChartInf(values);
    }
    //End
}
